### A Pluto.jl notebook ###
# v0.15.1

using Markdown
using InteractiveUtils

# ╔═╡ 926e4270-ee52-11eb-15b9-0b59dac4c681
using Pkg; Pkg.develop(path=".."); Pkg.activate("..")

# ╔═╡ 1d009b9d-dcf2-4bdf-8dd8-fef135cb8524
begin
	using SqState
	using QuantumStateBase
	using QuantumStatePlots
	using DataDeps
	using Plots
	using MAT
end;

# ╔═╡ 05865de0-1458-4c59-880c-8619d4c7dd83
md"
# Real time system

JingYu Ning

The real time quantum state tomogrophy system plays an important role in the homodyme experiment. It provides the features of data visualization without delay and get rid of the extremely complex data analasis works.

In this demonstration, we will show you how the data flows and how the machine learning model works.


"

# ╔═╡ d372a693-4a33-45b1-898c-72339f9e910f
md"
## A small yet elegant model

Apart from the intergration of the model implemented by HsenYi, the improvement of perforement is another essential part of real time system.

Therefore I implemented a small yet elegant CNN model that will infer the arguments `r`, `θ` and `n̄` for a squeezed thermal state to boost the inference process.
"

# ╔═╡ 7a22ff61-a32f-4def-9fd9-23a540791609
m = get_model("model")

# ╔═╡ 6f6ad264-cac8-4a04-906a-e83ebac85136
md"
## Experiment data from the lab

The experiments of the following data are accomplish by YiRu in NTHU
"

# ╔═╡ 1b4271a4-8540-4881-b6cb-7a3dd8e9d0b1
begin
	data_path = joinpath(datadep"SqState", "data/Flow")
	files = readdir(data_path)
end

# ╔═╡ 704a50f7-d093-4f5e-883a-8979b4ab930f
begin
	wf = WignerFunction(LinRange(-3, 3, 100), LinRange(-3, 3, 100), dim=35)

	function preprocess(data_name::String)
		# read data
		data_file = matopen(joinpath(datadep"SqState", "data/Flow/$data_name"))
		data = read(data_file, "data_sq")
		close(data_file)

		# sample
		data_indices = sort!(rand(1:size(data, 1), 4096))

		return data[data_indices, 1] # 1: x; 2: θ
	end

	function infer(data::Vector; dim=35)
		r, θ, n̄ = m(reshape(Float32.(data), (4096, 1, 1)))
		w = wf(SqueezedThermalState(ξ(r, 0.f0), n̄, dim=dim))

		return w
	end
end

# ╔═╡ 22a0af68-9012-4cc1-aebf-2f91bac387b4
md"
## About the data

The data is generated by the homodyme detector and capture by the oscilloscope.
"

# ╔═╡ 55d14429-f6e6-4db3-a7ea-6aec92fccd7d
data = preprocess("SQ20_5mW.mat")

# ╔═╡ 8bb50bb4-dbae-4adb-acd6-46dc45d8c109
md"
## Let the model do the magic

the model will infere the arguments for the state via the given quaduture data.
"

# ╔═╡ b015f3e0-89d8-4ecd-a3e5-23d9cc83a6e5
r, θ, n̄ = m(reshape(Float32.(data), (4096, 1, 1)))

# ╔═╡ d02b6dbc-a45d-4900-881a-30b550564f6d
md"
After the inference, we can construct the quantum state and plot the Wigner function, or apply some operator to it.
"

# ╔═╡ 90a4e898-f95a-4bd1-8825-9c7d8561a683
state = SqueezedThermalState(ξ(r, θ), n̄, dim=35)

# ╔═╡ d7756447-61ae-49f7-b0cb-ea1ff0432d29
plot_wigner(wf(state), Contour)

# ╔═╡ 5bb4f85c-af93-456c-af73-2dc069d0237a
md"
## Wigner flow
"

# ╔═╡ 3fdf7f29-b8b6-478b-9b4d-fb96407e99ae
begin
	anim = @animate for f in readdir(joinpath(datadep"SqState", "data/Flow"))
		plot_wigner(infer(preprocess(f)), QuantumStatePlots.Contour)
		annotate!(-2.5, 2.5, text("$f", :left))
	end

	gif(anim, fps=2)
end

# ╔═╡ Cell order:
# ╟─05865de0-1458-4c59-880c-8619d4c7dd83
# ╟─926e4270-ee52-11eb-15b9-0b59dac4c681
# ╠═1d009b9d-dcf2-4bdf-8dd8-fef135cb8524
# ╟─d372a693-4a33-45b1-898c-72339f9e910f
# ╠═7a22ff61-a32f-4def-9fd9-23a540791609
# ╟─6f6ad264-cac8-4a04-906a-e83ebac85136
# ╠═1b4271a4-8540-4881-b6cb-7a3dd8e9d0b1
# ╠═704a50f7-d093-4f5e-883a-8979b4ab930f
# ╟─22a0af68-9012-4cc1-aebf-2f91bac387b4
# ╠═55d14429-f6e6-4db3-a7ea-6aec92fccd7d
# ╟─8bb50bb4-dbae-4adb-acd6-46dc45d8c109
# ╠═b015f3e0-89d8-4ecd-a3e5-23d9cc83a6e5
# ╟─d02b6dbc-a45d-4900-881a-30b550564f6d
# ╠═90a4e898-f95a-4bd1-8825-9c7d8561a683
# ╠═d7756447-61ae-49f7-b0cb-ea1ff0432d29
# ╟─5bb4f85c-af93-456c-af73-2dc069d0237a
# ╠═3fdf7f29-b8b6-478b-9b4d-fb96407e99ae
